### ISSUE TITLE
font picker on Customizer broken

### ISSUE THREAD

**Issue by JohnRDOrazio** [BibleGet-I-O/bibleget-wordpress#18]
after recently refactoring all of the javascript to ES6 with arrow functions, `const` and `let` declarations, I am now finding that the font picker is broken in the Customizer settings area.

I'm seeing these errors in the console:

```console
jquery.fontselect.js:18 Uncaught SyntaxError: 'arguments' is not allowed in class field initializer or static initialization block
```
and

```console
Uncaught TypeError: $(...).fontselect is not a function
    at HTMLDocument.<anonymous> (fontselect-control.js?ver=6.4.3:2:29)
    at e (jquery.min.js:2:27028)
    at t (jquery.min.js:2:27330)
```

**Comment by JohnRDOrazio** [comment]
fixed in commits for release 8.1: https://github.com/BibleGet-I-O/bibleget-wordpress/compare/8.0...8.1
